Test (#15)

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -3,13 +3,13 @@ name: Test Pipeline
 on:
   push:
     branches:
-      - master
+      - test
   pull_request:
     branches:
       - master
 
 jobs:
-  Setup:
+  build:
     runs-on: ubuntu-latest
 
     steps:
@@ -25,15 +25,37 @@ jobs:
       - name: Install dependencies
         run: |
           npm install
-      
-      - name: Upload node_modules
-        uses: actions/upload-artifact@v3
-        with:
-          name: node_modules
-          path: node_modules
 
-  Build:
-    needs: Setup
+      - name: Build
+        run: |
+          npm run build
+
+  test:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        uses: actions/checkout@v3
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: 'npm'
+          cache: 'npm'
+
+      - name: Install dependencies
+        run: |
+          npm install
+      
+      - name: Unit test
+        run: |
+          npm run test      
+      
+  linting:
+    needs: test
     runs-on: ubuntu-latest
 
     steps:
@@ -45,7 +67,45 @@ jobs:
         with:
           node-version: 20
           cache: 'npm'
-          
-      - name: Build project
+
+      - name: Install dependencies
         run: |
-          npm run build
+          npm install
+
+      - name: Lint check
+        run: |
+          npm run lint
+
+  dependency-check:
+    needs: test
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: 'npm'
+
+      - name: Install dependencies
+        run: |
+          npm install
+
+      - name: Dependency check
+        run: |
+          npm audit --json > audit.json
+          # Check if any high severity vulnerabilities are found
+          if grep -q '"severity":"high"' audit.json; then
+            echo "High severity vulnerabilities found!"
+            exit 1  # Fail the workflow
+          else
+            echo "No high severity vulnerabilities found"
+          fi
